### PR TITLE
Navbar made grey

### LINKED ISSUE #71: Team Page Navbar
## Description
Navbar background can be made grey.

### Update [Required]
- [ ] [Navbar color changed]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

### PR DESCRIPTION
**Pull request by Sapna2001**
# Description
background of navbar changed to grey

Fixes #71 

# Type of Change:

- Code
- Quality Assurance
- User Interface

# How Has This Been Tested?
Tested on my local system

Screenshot
# Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by anubhavsingh16** [comment]
@Sapna2001 Please change the font family same as home page navbar.

**Comment by anubhavsingh16** [comment]
## Change from this Font ->
pr

# to this ->

pr

**Comment by Sapna2001** [comment]
font-family: 'Comfortaa', cursive; is used in both the pages. I don't know why the above font is showing up.

sc

**Comment by anubhavsingh16** [comment]
I think better than last one.

**Pull request merged**
