### PR TITLE
Background

### PR DESCRIPTION
**Pull request by Amankumar29**
background changed

### CODE REVIEW

**Comment by aashimgarg** [comment]
Screenshot from 2020-05-19 18-24-57

?

**Comment by Amankumar29** [comment]
Screenshot (10)
its working fine for me.

**Comment by aashimgarg** [comment]
> Screenshot (10)
> its working fine for me.

can you please add vendor prefixes to it so that it works fine for all the browsers,

**Comment by Amankumar29** [comment]
@anubhavsingh16 did you checked this?

**Comment by anubhavsingh16** [comment]
conflict error😣

**Comment by anubhavsingh16** [comment]
@Amankumar29 Thank you for this PR.

**Pull request closed without merging**
