### PR TITLE
Navbar-links addded

### LINKED ISSUE #74: Links navbar buttons
## Description
Link navbar buttons with respected pages. 

### Update [Required]
- [x] [Link all buttons of navbar with respected pages]
- [x] [Month button is not connected with month section]

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

### PR DESCRIPTION
**Pull request by Sapna2001**
# Description
Navbar links added in about.html,index.html and contact.html

Fixes #74 

# Type of Change:
- Code
- Quality Assurance
- User Interface

# How Has This Been Tested?
Tested locally.

# Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by Amankumar29** [comment]
do we have to link contact us page or just focus towards bottom only? @anubhavsingh16

**Comment by anubhavsingh16** [comment]
Bottom only

**Comment by Sapna2001** [comment]
I will link it to the bottom.

**Comment by Sapna2001** [comment]
I have changed it. Please review it.

**Pull request merged**
