### PR TITLE
Readme update

### LINKED ISSUE #92: Update Readme
## Description
Update Screenshot of website. Try to cover the important points.

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

### PR DESCRIPTION
**Pull request by Sapna2001**
# Description
Recent screenshots added to readme

Fixes #92 

# Type of Change:
- Documentation

# How Has This Been Tested?
Checked in local repo.

# Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by anubhavsingh16** [comment]
@Sapna2001 please add at max two screenshot and size must be small.

**Comment by Sapna2001** [comment]
Which all pages would you like to have.

**Comment by anubhavsingh16** [comment]
@Sapna2001 Use `Detail of events according to the month` and one screenshot which contains `information page and Home page`. And make both screenshots smaller in width and height https://gist.github.com/uupaa/f77d2bcf4dc7a294d109 this link helps you to resize the image.

**Comment by Sapna2001** [comment]
made the changes.

**Comment by anubhavsingh16** [comment]
@Sapna2001, Can you resend this PR after using git pull?

**Pull request closed without merging**
