### PR TITLE
navbar added

### LINKED ISSUE #61: Add navbar in Team page
## Description
The team page is not cleaned add navbar and proper indentation at top and bottom for quality look.

### Update [Required]
- [x] [Add navbar]
- [x] [Add padding at top and bottom]

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

### PR DESCRIPTION
**Pull request by Sapna2001**
# Description
Navbar added to the team Page

Fixes #61 

# Type of Change:
Navbar added

- Code
- Quality Assurance

# How Has This Been Tested?
Ran on my system.

Working Screenshot

# Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by Sapna2001** [comment]
Should I add some other color like grey to the navbar?

**Comment by Amankumar29** [comment]
@Sapna2001 good work 👍 
@aashimgarg @anubhavsingh16 have a look.

**Comment by anubhavsingh16** [comment]
Hmm merge this @Amankumar29

**Comment by anubhavsingh16** [comment]
> Should I add some other color like grey to the navbar?  

Sir light grey looks better i think 👌

**Pull request merged**
